### ISSUE TITLE
Dissemination based on secondary routing table

### ISSUE THREAD

**Issue by nulltea** [ChainSafe/das-prototype#15]
## Summary
- Implement samples dissemination using a secondary routing table (SRT)
- Preferably this should be a part of the custom discv5 overlay (see #14)
- It isn't yet clear what optimization can be made possible with SRT, but it is intuitive to see it as a way to spare requests by caching the location of DAS nodes and sample keys based on XOR-distance
- The data structure could either be a [`KBucketsTable`](https://github.com/sigp/discv5/blob/master/src/kbucket.rs#L148), or Protos DAS-tree, or something else.
- **Additional task 1:** consider using [uTP](https://github.com/ethereum/portal-network-specs/blob/master/discv5-utp.md) transport to send packets larger then plain UPD supports. It would be nice to compare that to current wire protocols (discv5, libp2p).
- **Additional task 2:** consider using [_neighborhood gossip_](https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md#neighborhood-gossip) to disperse samples bundles in short proximity of forwarders node_id, ie. instead of continuing split-and sending sample just flood the closest nodes with the whole bundle. It would be nice to see the impact of it on bucket-wise dissemination, but the implementation of it isn't strictly necessary.

**Comment by timoth-y** [comment]
Tree routing from [protolambda/dv5das](https://github.com/protolambda/dv5das) is based on binary prefix tree search.

Here is a brief guide how to implement it to our codebase:
- Add new batching strategy to enum: `BatchingStrategy::PrefixWise` which splits keys by first `P` bytes, see [dv5das#sampling-1](https://github.com/protolambda/dv5das#sampling-1)
- Ensure that DasTree is a prefix tree and init it in `setTopology` method similarly how it’s being updated on `Discv5Event::SessionEstablished` event
- Add `search_by_prefix` method to DasTree similar to this [tries-prefix-trees#prefix-search](https://www.baeldung.com/cs/tries-prefix-trees#prefix-search)
- On receiving the samples bundle apply `search_by_prefix` for each key and use `k` results (node_ids) to propagate samples further, at the result we should get `HashMap<NodeId, Vec<SampleKey>>` similar to how it’s done [here](https://github.com/ChainSafe/das-prototype/blob/main/src/main.rs#L1609)
- Add `PeerSorting` enum with values (`Random`, `ByScore`) and use it to sort `search_by_prefix` results before selecting `k` of them
- Add prefix-based lookup for sampling, see [dv5das#retrieving-samples](https://github.com/protolambda/dv5das#retrieving-samples),  TBD
